# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 89c148df9b639c92bd61f23f0c100f2b62681937db29b2ad21b859d24df9ddf0303a050b1e23920c5464fa55b4cfa07ce4b3cf65d922e4da2f082d3cde5deae9

test:
  secret_key_base: 289392db26beeebe50423001dd860069e4fb7ead680df757a6e122e603f3780120010336a15d44da226d5e78ee4990aa38c76009bd581f296de9b224a49b8a84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
